#
# to be placed in /usr/lib/sysctl.d/ & enabled on installation


# Details: https://docs.kernel.org/admin-guide/sysctl/net.html
# Details: https://wiki.archlinux.org/title/Security#BPF_hardening
# Minor / partially-related side note: Fedora's kernel is compiled 
# with `CONFIG_BPF_JIT_ALWAYS_ON`=True
net.core.bpf_jit_harden = 2

# Details: https://docs.kernel.org/admin-guide/LSM/Yama.html
# Details: https://wiki.archlinux.org/title/Security#ptrace_scope
# This adds a mostly redundant security layer to "setsebool -P deny_ptrace on"
# (see "downstream-hardening.install.sh"): this will likely break applications
# like "gdb" or "strace" given their need for ptrace for obvious reasons:
# it can allow processes to access data of other processes, which leads
# to several use cases of ptrace in hostile exploitation (e.g., to
# access secrets / credentials stored in other processes memory, which during
# runtime is not encrypted, even if the disk is encrypted)
kernel.yama.ptrace_scope = 2

# Details: https://docs.kernel.org/admin-guide/sysctl/kernel.html#kptr-restrict
# Details: https://wiki.archlinux.org/title/Security#Restricting_access_to_kernel_pointers_in_the_proc_filesystem
# This is formally not adding security as Fedora and its downstream use a
# pre-compiled kernel, but in vulnerable situations, this massively increases
# the necessary knowledge and understanding for attempts of hostile exploitation
kernel.kptr_restrict = 2

# This is unlikely to cause exploitable attack surface in average use cases
# of OS that are appropriately pre-configured, but for the same reason it is
# unlikely to cause issues to the users.
# In case of a doubt, it mitigates some potential for attack surface, including
# some attack surface the user might create themselves by accident. Even if the
# latter applies, it is unlikely to cause an impact except mitigate exploitation
# Details: https://docs.kernel.org/admin-guide/sysctl/fs.html#protected-fifos
fs.protected_fifos = 2
# Details: https://docs.kernel.org/admin-guide/sysctl/fs.html#protected-regular
fs.protected_regular = 2
