#!/usr/bin/bash

# This has been obsoleted by the file "harden"

"""
# The following is to ensure that root remains unconfined_u, which should be a default,
# but given the potential impact, this needs to be ensured:
# the two commands cannot impact if root is already set unconfined_u
semanage login -a -s unconfined_u root
semanage login -m -s unconfined_u root
# The following ensures that accounts that are not explicitly excluded
# from confinement will be given minimal privileges and confined as user_u by SELinux
semanage login -m -s user_u -r s0 __default__
# This is to remove open ports, which are usually not necessary for desktop/workstation
# use cases. This aims to keep other and default parameter of different OS, editions,
# spins, variants, etc. in place and make it possible to re-establish the previous
# port configuration of the very OS edition/spin/variant later.
# Do not use "--reset-to-defaults" because this is leads to a general default of
# firewalld and not the default of the very OS edition/spin/variant.
sed -i.old0 '/port port/d' /etc/firewalld/zones/*.xml
rename .xml .hardened.xml /etc/firewalld/zones/*.xml
firewall-cmd --reload
# This adds a mostly redundant security layer to "kernel.yama.ptrace_scope"
# (see "99-downstream-hardening"): this will likely break applications
# like "gdb" or "strace" given their need for ptrace for obvious reasons:
# it can allow processes to access data of other processes, which leads
# to several use cases of ptrace in hostile exploitation (e.g., to
# access secrets / credentials stored in other processes memory, which during
# runtime is not encrypted, even if the disk is encrypted)
setsebool -P deny_ptrace on
# Trigger the python3 script once to introduce the confinement after installation
python3 /usr/bin/unconfinehomeusers
# Enable the path file that was installed by the package
# (it triggers the service file on demand)
systemctl enable unconfinehomeusers.path
# Create the harden state to indicate future invocations harden is activated.
# This will be relevant also for updates.
mkdir /etc/harden
echo "# This file is auto-generated by the tool \"harden\"" >> /etc/harden/harden
echo "# Do NOT edit directly. Do only use the tool!" >> /etc/harden/harden
echo "#" >> /etc/harden/harden
echo "# Changing this file will not have an effect on itself!" >> /etc/harden/harden
echo "# This file serves only as indicator for \"harden\"" >> /etc/harden/harden
echo "# when \"Harden\" is invoked by other means." >> /etc/harden/harden
echo "#" >> /etc/harden/harden
echo "# Modifying this file directly can lead to unintended behavior!" >> /etc/harden/harden
echo "True" >> /etc/harden/harden
"""
