#!/usr/bin/bash

#    This tool is an interface to activate, disable and test the hardening
#    Copyright (C) 2026  Christopher Klooz
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# This is the major executable for the "harden" tool:
# Use this to activate the hardening on your system
# and to deactivate it again
#
# The tool also supports an update function, which updates
# the conditions of "harden" to changed/new circumstances:
# once the script is "activated", it will AUTOMATICALLY UPDATE
# its conditions once the rpm package is updated by "dnf":
# no user update necessary after activation!
#
# Most updates will occur automatically (e.g., by changing
# existing conf files) without this tool: they will automatically
# apply after rebooting. Yet, it is possible that some future updates
# cannot be done only by adjusting file contents: the update
# function will be implemented and get adjusted if future
# updates will make changes necessary that cannot be done by adjusting files:
# e.g., when new SELinux booleans need to be enabled and old ones disabled (it is
# not a good practice to adjust the related files directly for several reasons).
#
# If you uninstall "harden" package at all with "dnf",
# "dnf" will once run this script with the -d (deactivate)
# option before uninstalling the remaining package
#
# When doing any change in this file, ensure to update the selftests
# in "harden-selftest" correspondingly! (E.g., when adding new binaries)

# IMPLEMENT TWO CHECKS THAT ARE ENFORCED BEFORE ACTIVATING:
# - check if sudo/root -> root necessary!
# - check if activation has already be done -> don't rerun activation if already activated!
#   -> check for the FILE /usr/share/doc/Fedora-downstream-hardening/99-kernel-hardening.conf

# IMPLEMENT TWO CHECKS THAT ARE ENFORCED BEFORE DEACTIVATING:
# - check if sudo/root -> root necessary!
# - check if activation has already be done -> run deactivation only if currently activated!
#   -> check for the SYMLINK /usr/lib/sysctl.d/99-kernel-hardening.conf

# WHEN THE PACKAGE IS RENAMED in version 1.0, BELOW THE PATHS
# /etc/dnf/protected.d/Fedora-downstream-hardening.conf and
# /usr/share/doc/Fedora-downstream-hardening/ NEED TO BE ADJUSTED

if [ "$EUID" -ne 0 ]
    then
        echo "This tool needs to run with sudo or as root"
        exit
elif [ "$1" == "activate" ]
    then
        # The following is to ensure that root remains unconfined_u, which should be a default,
        # but given the potential impact, this needs to be ensured:
        # the two commands cannot impact if root is already set unconfined_u
        semanage login -a -s unconfined_u root
        semanage login -m -s unconfined_u root
        # Any confinement on __default__ has been removed in the commits before 0.9
        # in order to mitigate Fedora's limited capacity to identify bugs and
        # SELinux policy issues related to SELinux user confinement of __default__:
        # the new approach keeps __default__ on unconfined_u to avoid updates or
        # customizations to break the system of users: confinement is now selective and
        # takes place exclusively through "unconfinehomeusers"
        unconfinehomeusers
        # This is to remove open ports, which are usually not necessary for desktop/workstation
        # use cases. This aims to keep other and default parameter of different OS, editions,
        # spins, variants, etc. in place and make it possible to re-establish the previous
        # port configuration of the very OS edition/spin/variant later.
        # Do not use "--reset-to-defaults" because this is leads to a general default of
        # firewalld and not the default of the very OS edition/spin/variant.
        if ! test -e /etc/firewalld/firewalld.conf.prehardening;
            then
                cp /etc/firewalld/firewalld.conf /etc/firewalld/firewalld.conf.prehardening
                echo "*.prehardening files are created by the tool \"harden\" to retain the" > /etc/firewalld/firewalld-prehardening-README.txt
                echo "state of the firewalld of the time before the hardening, in order to" >> /etc/firewalld/firewalld-prehardening-README.txt
                echo "re-establish that state later. Do NOT change these files!" >> /etc/firewalld/firewalld-prehardening-README.txt
                echo "They will be automatically used and then deleted when the hardening" >> /etc/firewalld/firewalld-prehardening-README.txt
                echo "is deactivated with \"harden deactivate\"" >> /etc/firewalld/firewalld-prehardening-README.txt
                echo "" >> /etc/firewalld/firewalld-prehardening-README.txt
                echo "If you read this file, whereas the file" >> /etc/firewalld/firewalld-prehardening-README.txt
                echo "/etc/firewalld/firewalld.conf.prehardening is no longer existing," >> /etc/firewalld/firewalld-prehardening-README.txt
                echo "then something went wrong, and if you did not delete it yourself," >> /etc/firewalld/firewalld-prehardening-README.txt
                echo "you should consider opening a bug report about this." >> /etc/firewalld/firewalld-prehardening-README.txt
        else
            echo "It seems harden is already partially or fully activated. This tool"
            echo "will now try to re-establish the full hardening, in case hardening has been"
            echo "partially deactivated, but if you are unsure why this message occurs, it is"
            echo "suggested to reboot after this tool has finished and then do \"sudo harden"
            echo "selftest\" and then follow the instructions of the selftest if it fails."
            echo "If harden is already fully activated and you run this activation by "
            echo "accident, everything is fine and this invocation will have no impact."
            echo ""
        fi
        firewall-cmd --set-default-zone=public
        firewall-cmd --reload
        # Enable the file "99-kernel-hardening.conf" by linking it from
        # "/usr/share/doc/Fedora-downstream-hardening/" to
        # "/etc/sysctl.d/": details in the file
        # Note: /usr/lib/sysctl.d/ has been replaced in 0.7 by /etc/sysctl.d/ to achieve
        # compatibility with immutable variants, which is not given otherwise due to
        # the "harden activation" taking place after installation/overlay of the package
        ln -s /usr/share/doc/fedora-downstream-hardening/99-kernel-hardening.conf /etc/sysctl.d/
        # This adds a mostly redundant security layer to "kernel.yama.ptrace_scope"
        # (see "99-downstream-hardening"): this will likely break applications
        # like "gdb" or "strace" given their need for ptrace for obvious reasons:
        # it can allow processes to access data of other processes, which leads
        # to several use cases of ptrace in hostile exploitation (e.g., to
        # access secrets / credentials stored in other processes memory, which during
        # runtime is not encrypted, even if the disk is encrypted)
        setsebool -P deny_ptrace on
        # Trigger the python3 script once to introduce the confinement after installation
        python3 /usr/bin/unconfinehomeusers
        # Enable the path file that was installed by the package
        # (it triggers the service file on demand)
        systemctl enable unconfinehomeusers.path
        # Ensure that the hardening configuration gets updated if its rpm package is updated,
        # in order to ensure the hardening configuration is always tailored to current
        # circumstances and to the then-up-to-date Fedora release
        systemctl enable hardenupdate.path
        # Protect this package to ensure it is not removed by rpm/dnf as long as it is
        # activated! The reason is that removing the package's files can cause
        # unintended behavior if the changes of activation are not reverted.
        # E.g., without a preceding deactivation, the hardened state
        # of "semanage login -l" would remain, but the tool that adjusts it,
        # when new user accounts are created, would be gone: thus, future accounts
        # would be mapped to __default__ and therefore highly confined: this is assumed
        # unintended for most users. There are other impacts possible as well!
        # Correspondingly, do not change the protected status yourself, but just
        # deactivate harden with "harden deactivate": this will remove the protected
        # status automatically!
        # The protection might become relevant also for updates: it documents
        # if the hardening is currently activated or not
        echo "fedora-downstream-hardening" > /etc/dnf/protected.d/fedora-downstream-hardening.conf
        echo ""
        echo "Activation done! Please reboot now! After rebooting, it is suggested to run the"
        echo "selftest by invoking the tool \"harden-selftest\": while the hardening is"
        echo "intended to update itself automatically after the package and the contained tool"
        echo "have been updated by your daily updates, it is still useful"
        echo "to occasionally (e.g., after release upgrades) re-run the selftest"
        echo "to verify the hardening is still configured and up to date as intended!"
        echo ""
        echo "If \"harden\" breaks anything that should not be broken, or if the selftest"
        echo "fails at some time, feel free to open a ticket at the Security SIG:"
        echo "https://forge.fedoraproject.org/security"
        echo ""
        echo "IMPORTANT for admins who customize their SELinux User Confinement:"
        echo "Every account that exists in /home/ and in /etc/passwd (if with /bin/bash) will"
        echo "be separated from __default__ automatically, which means you need to define their"
        echo "separated entry with user_u: __default__ will not apply to such accounts!"
        echo "If you do not customize SELinux User Confinement (or: if you do not work with"
        echo "commands like \"semanage login ...\"), you can ignore this IMPORTANT message."
        echo ""
        echo "If you fear you or other users might accidentally run malicious files sent by,"
        echo "e.g., email, and want to mitigate this to happen by accident and by a single"
        echo "\"double click\", you might want to add the \"noexec\" option to /tmp and"
        echo "/home. Keep in mind this will make it impossible to run applications that are"
        echo "downloaded and stored by a normal user in the directories they can write in."
        echo "Also, keep in mind a user with basics in how Linux works can intentionally bypass"
        echo "this option: noexec is intended to support the trusted but maybe inexperienced"
        echo "or unperceptive user, not to protect against malicious untrusted users."
        echo "you can enable this with the following command and then reboot:"
        echo "\"sudo harden activate-noexec-now\""
        echo "You can disable it with the following command and then reboot:"
        echo "\"sudo harden deactivate-noexec-now\""
        echo ""
elif [ "$1" == "deactivate" ]
    then
        # The following revokes the changes of "activate".
        # It does not delete "all entries" but "all customizations":
        # it will re-create the defaults / default entries
        semanage login --deleteall
        # The following revokes the changes of "activate".
        # with regards to open/closed ports
        if test -e /etc/firewalld/firewalld.conf.prehardening;
            then
                # The prehardening file is intentionally not re-used, to ensure that updates
                # of Fedora, which happened in the meantime, are not overwritten: the well tested,
                # maintained and evaluated verifications and tests of "firewall-cmd" shall be deployed,
                # changing the zone in the same way as it was changed in the first place.
                originalzone=$(cat /etc/firewalld/firewalld.conf.prehardening |  grep '^DefaultZone=' | head -n 1 | cut -c13-)
                if firewall-cmd --list-all-zones | grep -Fx $originalzone;
                    then
                        firewall-cmd --set-default-zone=$originalzone
                        firewall-cmd --reload
                        rm -f /etc/firewalld/firewalld.conf.prehardening
                        rm -f /etc/firewalld/firewalld-prehardening-README.txt
                else
                    echo "Your original firewall zone is no longer supported by the firewall"
                    echo "or the file /etc/firewalld/firewalld.conf.prehardening has been modified. This is likely not a serious"
                    echo "issue. \"harden\" will leave the current profile active: if the preceding \"harden selftest\""
                    echo "was successful, the profile is still the protective \"public\" profile."
                    echo "This profile should suffice also in non-hardened use cases and resembles what many OS"
                    echo "have by default. If you worry, open a ticket in ask.fedora to change your profile. The files"
                    echo "firewalld.conf.prehardening and firewalld-prehardening-README.txt are retained for potential use"
                    echo "in troubleshooting. If you think any of this is not correct, consider to open a bug report about this."
                    echo "It is suggested to open a bug report in general if the"
                    echo "next line is empty or contains either = or multiple terms with a space in between, except after the space is #"
                    echo "$originalzone "
                    echo "Please mention in your report the error type name -commandline_fwPrehardeningZoneNA-"
                    echo "If you open a bug report, store and add the following lines in between the ----- if not empty:"
                    echo "-----"
                    cat /etc/firewalld/firewalld.conf | grep DefaultZone=Public
                    echo "###"
                    ls /etc/firewalld/firewalld.conf.prehardening
                    ls /etc/firewalld/firewalld-prehardening-README.txt
                    echo "-----"
                fi
        else
            echo "It seems harden is not activated, or the backup of the original pre-hardening firewall zone"
            echo "has been modified or deleted. If harden had been activated and a preceding \"harden selftest\""
            echo "was successful, the firewall is still set to the protective profile \"public\"."
            echo "If you are sure that harden was activated, and if it was not you who modified or"
            echo "deleted the file /etc/firewalld/firewalld.conf.prehardening, consider to open a bug report about this."
            echo "Please mention in your report the error type name -commandline_fwPrehardeningFileDeleted-"
            echo "This is likely not a serious issue. This profile should suffice also in non-hardened use cases and"
            echo "resembles what many OS have by default. If you worry, open a ticket in ask.fedora to change your profile."
            echo "If you open a bug report, store and add the following lines in between the ----- if not empty:"
            echo "-----"
            cat /etc/firewalld/firewalld.conf | grep DefaultZone=Public
            echo "###"
            ls /etc/firewalld/firewalld.conf.prehardening
            ls /etc/firewalld/firewalld-prehardening-README.txt
            echo "-----"
        fi
        # Remove the link of "/usr/share/doc/Fedora-downstream-hardening/99-kernel-hardening.conf"
        # to "/etc/sysctl.d/" in order to disable the file
        rm -fr /etc/sysctl.d/99-kernel-hardening.conf
        # The following revokes the changes of "activate".
        # with regards to the SELinux boolean that blocks ptrace redundantly
        # with YAMA
        setsebool -P deny_ptrace off
        # Disable unconfinehomeusers.path: the path+service files remain available
        # and can be re-activated/re-enabled as long as the package is installed
        systemctl disable unconfinehomeusers.path
        # Disable the auto-updates of the hardening configuration:
        # they are only necessary while the hardening is activated.
        # This is NOT related to the updates of the hardening rpm package
        systemctl disable hardenupdate.path
        # Once deactivated, the package no longer needs to be protected
        rm -fr /etc/dnf/protected.d/fedora-downstream-hardening.conf
        echo "Now harden is deactivated. If you had also activated \"harden activate-noexec-now,\","
        echo "then you have to disable this separately with \"harden deactivate-noexec-now\""
        echo "\"\""
elif [ "$1" == "activate-noexec-now" ]
    then
        if systemctl cat tmp.mount | grep -q "# /usr/lib/systemd/system/tmp.mount";
            then
                mkdir /etc/systemd/system/tmp.mount.d
                echo "[Mount]" > /etc/systemd/system/tmp.mount.d/override.conf
                systemctl cat tmp.mount | grep Options= | sed '${s/$/,noexec/}' >> /etc/systemd/system/tmp.mount.d/override.conf
                systemctl daemon-reload
        else
            echo "It seems you have modified your system and the automated noexec on /tmp no longer works"
            echo "If you think your system is a default, you might want to open a bug ticket about this!"
        fi
        if systemctl cat home.mount | grep -q "# /run/systemd/generator/home.mount";
            then
                mkdir /etc/systemd/system/home.mount.d
                echo "[Mount]" > /etc/systemd/system/home.mount.d/override.conf
                systemctl cat home.mount | grep Options= | sed '${s/$/,noexec/}' >> /etc/systemd/system/home.mount.d/override.conf
                systemctl daemon-reload
        elif systemctl cat var-home.mount | grep -q "# /run/systemd/generator/var-home.mount";
            then
                mkdir /etc/systemd/system/var-home.mount.d
                echo "[Mount]" > /etc/systemd/system/var-home.mount.d/override.conf
                systemctl cat var-home.mount | grep Options= | sed '${s/$/,noexec/}' >> /etc/systemd/system/var-home.mount.d/override.conf
                systemctl daemon-reload
        else
            echo "It seems you have modified your system and the automated noexec on /home no longer works"
            echo "If you think your system is a default, you might want to open a bug ticket about this!"
        fi
elif [ "$1" == "deactivate-noexec-now" ]
    then
        if ls /etc/systemd/system/tmp.mount.d/override.conf 2> /dev/null | grep -q "override.conf"
            then
                rm -f /etc/systemd/system/tmp.mount.d/override.conf > /dev/null
                if [ -z "$( ls -A '/etc/systemd/system/tmp.mount.d/' )" ];
                    then
                        rm -fr /etc/systemd/system/tmp.mount.d/ > /dev/null
                fi
                systemctl daemon-reload
                echo "noexec is now disabled on /tmp"
        else
            echo "It seems harden activate-noexec-now was not enabled on /tmp.";
        fi
        if ls /etc/systemd/system/home.mount.d/override.conf 2> /dev/null | grep -q "override.conf"
            then
                rm -f /etc/systemd/system/home.mount.d/override.conf > /dev/null
                if [ -z "$( ls -A '/etc/systemd/system/home.mount.d/' )" ];
                    then
                        rm -fr /etc/systemd/system/home.mount.d/ > /dev/null
                fi
                systemctl daemon-reload
                echo "noexec is now disabled on /home"
        elif ls /etc/systemd/system/var-home.mount.d/override.conf 2> /dev/null | grep -q "override.conf"
            then
                rm -f /etc/systemd/system/var-home.mount.d/override.conf > /dev/null
                if [ -z "$( ls -A '/etc/systemd/system/var-home.mount.d/' )" ];
                    then
                        rm -fr /etc/systemd/system/var-home.mount.d/ > /dev/null
                fi
                systemctl daemon-reload
                echo "noexec is now disabled on /home"
        else
            echo "It seems harden activate-noexec-now was not enabled on /home.";
        fi
elif [ "$1" == "update" ]
    then
        # Read the comments above in this file: this will be implemented on demand.
        # If applicable at some time, the rpm package will update this file and
        # this section through dnf, and it will be invoked on demand automatically.
        # It might become useful to create a separate python script that is invoked
        # by this elif.
        echo "This function is currently not necessary. This function is not intended"
        echo "to be invoked manually by users: both the hardening tools, and"
        echo "the hardening that these tools activated/implemented on a given system at"
        echo "any time, will be automatically updated with your daily updates!"
        echo "Users do NOT need to update their hardening configuration or"
        echo "the hardening tools on themselves!"
        echo "Read the comments (lines beginning with #) in the file /usr/bin/harden:"
        echo "This function will be implemented on demand. If applicable at some time, the"
        echo "rpm package will update this file and this section through dnf automatically,"
        echo "and updates will then be invoked on demand automatically as well."
        echo "Most hardening updates are implemented through adjusting files and thus do"
        echo "not rely on this update function but automatically apply after rebooting."
        echo "This function exists currently only as precaution in case some future"
        echo "updates cannot be fully implemented by adjusting files."
        echo "Users can rely on just doing once \"harden activate\" and then do their"
        echo "daily updates."
elif [ "$1" == "license" ]
    then
        # Read the comments above in this file: this will be implemented on demand.
        # If applicable at some time, the rpm package will update this file and
        # this section through dnf, and it will be invoked on demand automatically.
        # It might become useful to create a separate python script that is invoked
        # by this elif.
        echo "This program is free software; you can redistribute it and/or modify"
        echo "it under the terms of the GNU General Public License as published by"
        echo "the Free Software Foundation; either version 2 of the License, or"
        echo "(at your option) any later version."
        echo ""
        echo "This program is distributed in the hope that it will be useful,"
        echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
        echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
        echo "GNU General Public License for more details."
        echo ""
        echo "You should have received a copy of the GNU General Public License along"
        echo "with this program; if not, write to the Free Software Foundation, Inc.,"
        echo "51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA."
elif [ "$1" == "selftest" ]
    then
        # This is equal to running the selftest "harden-selftest" from the command line
        # Read the comments (lines beginning with #) in the file "/usr/bin/harden-selftest"
        harden-selftest
else
        echo "This tool only supports \"activate\", \"selftest\", \"license\" and \"deactivate\""
        echo "The \"selftest\" of \"harden\" is equal to running the tool"
        echo "\"harden-sefltest\": \"harden selftest\" actually just invokes \"harden-selftest\""
        echo "\"activate-noexec-now\" and \"deactivate-noexec-now\" are available as well but should"
        echo "be used only after having activated harden in the first place and after carefully"
        echo "reading the output of harden activate, or if you know exactly what you do!"
        echo "Read the comments (lines beginning with #) in the file /usr/bin/harden"
        echo ""
        echo "More information about this tool, and the package it belongs to, can be found at:"
        echo "https://github.com/py0xc3/Fedora-downstream-hardening/"
fi




