#!/usr/bin/bash

#    This tool is an interface to activate, disable and test the hardening
#    Copyright (C) 2026  Christopher Klooz
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# This is the major executable for the "harden" tool:
# Use this to activate the hardening on your system
# and to deactivate it again
#
# The tool also supports an update function, which updates
# the conditions of "harden" to changed/new circumstances:
# once the script is "activated", it will AUTOMATICALLY UPDATE
# its conditions once the rpm package is updated by "dnf":
# no user update necessary after activation!
#
# Most updates will occur automatically (e.g., by changing
# existing conf files) without this tool: they will automatically
# apply after rebooting. Yet, it is possible that some future updates
# cannot be done only by adjusting file contents: the update
# function will be implemented and get adjusted if future
# updates will make changes necessary that cannot be done by adjusting files:
# e.g., when new SELinux booleans need to be enabled and old ones disabled (it is
# not a good practice to adjust the related files directly for several reasons).
#
# If you uninstall "harden" package at all with "dnf",
# "dnf" will once run this script with the -d (deactivate)
# option before uninstalling the remaining package
#
# When doing any change in this file, ensure to update the selftests
# in "harden-selftest" correspondingly! (E.g., when adding new binaries)

# IMPLEMENT TWO CHECKS THAT ARE ENFORCED BEFORE ACTIVATING:
# - check if sudo/root -> root necessary!
# - check if activation has already be done -> don't rerun activation if already activated!
#   -> check for the FILE /usr/share/doc/Fedora-downstream-hardening/99-kernel-hardening.conf

# IMPLEMENT TWO CHECKS THAT ARE ENFORCED BEFORE DEACTIVATING:
# - check if sudo/root -> root necessary!
# - check if activation has already be done -> run deactivation only if currently activated!
#   -> check for the SYMLINK /usr/lib/sysctl.d/99-kernel-hardening.conf

# WHEN THE PACKAGE IS RENAMED in version 1.0, BELOW THE PATHS
# /etc/dnf/protected.d/Fedora-downstream-hardening.conf and
# /usr/share/doc/Fedora-downstream-hardening/ NEED TO BE ADJUSTED

if [ "$EUID" -ne 0 ]
    then
        echo "This tool needs to run with sudo or as root"
        exit
elif [ "$1" == "activate" ]
    then
        # The following is to ensure that root remains unconfined_u, which should be a default,
        # but given the potential impact, this needs to be ensured:
        # the two commands cannot impact if root is already set unconfined_u
        semanage login -a -s unconfined_u root
        semanage login -m -s unconfined_u root
        # The following ensures that accounts that are not explicitly excluded
        # from confinement will be given minimal privileges and confined as user_u by SELinux
        semanage login -m -s user_u -r s0 __default__
        # This is to remove open ports, which are usually not necessary for desktop/workstation
        # use cases. This aims to keep other and default parameter of different OS, editions,
        # spins, variants, etc. in place and make it possible to re-establish the previous
        # port configuration of the very OS edition/spin/variant later.
        # Do not use "--reset-to-defaults" because this is leads to a general default of
        # firewalld and not the default of the very OS edition/spin/variant.
        if ! test -d /etc/firewalld/zones.pre-hardening/;
            then
                mkdir /etc/firewalld/zones.pre-hardening/
                mkdir /etc/firewalld/conf.pre-hardening/
                cp /etc/firewalld/zones/* /etc/firewalld/zones.pre-hardening/
                cp /etc/firewalld/*.conf /etc/firewalld/conf.pre-hardening/
                rm -fr /etc/firewalld/zones/
        else
            echo "It seems harden is already partially or fully activated. This tool"
            echo "will now try to re-establish the full hardening, in case hardening has been"
            echo "partially deactivated, but if you are unsure why this message occurs, it is"
            echo "suggested to reboot after this tool has finished and then do \"sudo harden"
            echo "selftest\" and then follow the instructions of the selftest if it fails."
            echo "If harden is already fully activated and you run this activation by "
            echo "accident, everything is fine and this invocation will have no impact."
            echo ""
        fi
        cp -r /etc/firewalld/zones /etc/firewalld/zones.pre-hardening
#        firewall-cmd --remove-port=0-65535/tcp --permanent
#        firewall-cmd --remove-port=0-65535/udp --permanent
        firewall-cmd --set-default-zone=public
        firewall-cmd --reload
        # Enable the file "99-kernel-hardening.conf" by linking it from
        # "/usr/share/doc/Fedora-downstream-hardening/" to
        # "/etc/sysctl.d/": details in the file
        # Note: /usr/lib/sysctl.d/ has been replaced in 0.7 by /etc/sysctl.d/ to achieve
        # compatibility with immutable variants, which is not given otherwise due to
        # the "harden activation" taking place after installation/overlay of the package
        ln -s /usr/share/doc/Fedora-downstream-hardening/99-kernel-hardening.conf /etc/sysctl.d/
        # This adds a mostly redundant security layer to "kernel.yama.ptrace_scope"
        # (see "99-downstream-hardening"): this will likely break applications
        # like "gdb" or "strace" given their need for ptrace for obvious reasons:
        # it can allow processes to access data of other processes, which leads
        # to several use cases of ptrace in hostile exploitation (e.g., to
        # access secrets / credentials stored in other processes memory, which during
        # runtime is not encrypted, even if the disk is encrypted)
        setsebool -P deny_ptrace on
        # Trigger the python3 script once to introduce the confinement after installation
        python3 /usr/bin/unconfinehomeusers
        # Enable the path file that was installed by the package
        # (it triggers the service file on demand)
        systemctl enable unconfinehomeusers.path
        # Ensure that the hardening configuration gets updated if its rpm package is updated,
        # in order to ensure the hardening configuration is always tailored to current
        # circumstances and to the then-up-to-date Fedora release
        systemctl enable hardenupdate.path
        # Protect this package to ensure it is not removed by rpm/dnf as long as it is
        # activated! The reason is that removing the package's files can cause
        # unintended behavior if the changes of activation are not reverted.
        # E.g., without a preceding deactivation, the hardened state
        # of "semanage login -l" would remain, but the tool that adjusts it,
        # when new user accounts are created, would be gone: thus, future accounts
        # would be mapped to __default__ and therefore highly confined: this is assumed
        # unintended for most users. There are other impacts possible as well!
        # Correspondingly, do not change the protected status yourself, but just
        # deactivate harden with "harden deactivate": this will remove the protected
        # status automatically!
        # The protection might become relevant also for updates: it documents
        # if the hardening is currently activated or not
        echo "Fedora-downstream-hardening" > /etc/dnf/protected.d/Fedora-downstream-hardening.conf
        echo "Activation done! Please reboot now! After rebooting, it is suggested to run the"
        echo "selftest by invoking the tool \"harden-selftest\": while the hardening is"
        echo "intended to update itself automatically after the package and the contained tool"
        echo "have been updated by your daily updates, it is still useful"
        echo "to occasionally (e.g., after release upgrades) re-run the selftest"
        echo "to verify the hardening is still configured and up to date as intended!"
        echo ""
        echo "If \"harden\" breaks anything that should not be broken, or if the selftest"
        echo "fails at some time, feel free to open a ticket at the Security SIG:"
        echo "https://forge.fedoraproject.org/security"
        echo ""
        echo "IMPORTANT for admins who customize their SELinux User Confinement:"
        echo "Every account that exists in /home/ and in /etc/passwd (if with /bin/bash) will"
        echo "be separated from __default__ automatically, which means you need to define their"
        echo "separated entry with user_u: __default__ will not apply to such accounts!"
        echo "If you do not customize SELinux User Confinement (or: if you do not work with"
        echo "commands like \"semanage login ...\"), you can ignore this IMPORTANT message."
elif [ "$1" == "deactivate" ]
    then
        # The following revokes the changes of "activate".
        # It does not delete "all entries" but "all customizations":
        # it will re-create the defaults / default entries
        semanage login --deleteall
        # The following revokes the changes of "activate".
        # with regards to open/closed ports
        if test -d /etc/firewalld/zones.pre-hardening/;
            then
                rm -f /etc/firewalld/*.conf
                cp /etc/firewalld/conf.pre-hardening/* /etc/firewalld/
                rm -fr /etc/firewalld/conf.pre-hardening/
                rm -f /etc/firewalld/zones/*
                cp /etc/firewalld/zones.pre-hardening/* /etc/firewalld/zones/
                rm -fr /etc/firewalld/zones.pre-hardening/
                firewall-cmd --reload
        fi
        # Remove the link of "/usr/share/doc/Fedora-downstream-hardening/99-kernel-hardening.conf"
        # to "/etc/sysctl.d/" in order to disable the file
        rm -fr /etc/sysctl.d/99-kernel-hardening.conf
        # The following revokes the changes of "activate".
        # with regards to the SELinux boolean that blocks ptrace redundantly
        # with YAMA
        setsebool -P deny_ptrace off
        # Disable unconfinehomeusers.path: the path+service files remain available
        # and can be re-activated/re-enabled as long as the package is installed
        systemctl disable unconfinehomeusers.path
        # Disable the auto-updates of the hardening configuration:
        # they are only necessary while the hardening is activated.
        # This is NOT related to the updates of the hardening rpm package
        systemctl disable hardenupdate.path
        # Once deactivated, the package no longer needs to be protected
        rm -fr /etc/dnf/protected.d/Fedora-downstream-hardening.conf
elif [ "$1" == "update" ]
    then
        # Read the comments above in this file: this will be implemented on demand.
        # If applicable at some time, the rpm package will update this file and
        # this section through dnf, and it will be invoked on demand automatically.
        # It might become useful to create a separate python script that is invoked
        # by this elif.
        echo "This function is currently not necessary. This function is not intended"
        echo "to be invoked manually by users: both the hardening tools, and"
        echo "the hardening that these tools activated/implemented on a given system at"
        echo "any time, will be automatically updated with your daily updates!"
        echo "Users do NOT need to update their hardening configuration or"
        echo "the hardening tools on themselves!"
        echo "Read the comments (lines beginning with #) in the file /usr/bin/harden:"
        echo "This function will be implemented on demand. If applicable at some time, the"
        echo "rpm package will update this file and this section through dnf automatically,"
        echo "and updates will then be invoked on demand automatically as well."
        echo "Most hardening updates are implemented through adjusting files and thus do"
        echo "not rely on this update function but automatically apply after rebooting."
        echo "This function exists currently only as precaution in case some future"
        echo "updates cannot be fully implemented by adjusting files."
        echo "Users can rely on just doing once \"harden activate\" and then do their"
        echo "daily updates."
elif [ "$1" == "license" ]
    then
        # Read the comments above in this file: this will be implemented on demand.
        # If applicable at some time, the rpm package will update this file and
        # this section through dnf, and it will be invoked on demand automatically.
        # It might become useful to create a separate python script that is invoked
        # by this elif.
        echo "This program is free software; you can redistribute it and/or modify"
        echo "it under the terms of the GNU General Public License as published by"
        echo "the Free Software Foundation; version 2 only"
        echo ""
        echo "This program is distributed in the hope that it will be useful,"
        echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
        echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
        echo "GNU General Public License for more details."
        echo ""
        echo "You should have received a copy of the GNU General Public License along"
        echo "with this program; if not, write to the Free Software Foundation, Inc.,"
        echo "51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA."
elif [ "$1" == "selftest" ]
    then
        # This is equal to running the selftest "harden-selftest" from the command line
        # Read the comments (lines beginning with #) in the file "/usr/bin/harden-selftest"
        harden-selftest
else
        echo "This tool only supports \"activate\", \"selftest\", \"license\" and \"deactivate\""
        echo "The \"selftest\" of \"harden\" is equal to running the tool"
        echo "\"harden-sefltest\": \"harden selftest\" actually just invokes \"harden-selftest\""
        echo "Read the comments (lines beginning with #) in the file /usr/bin/harden"
fi




