#!/usr/bin/python3

#    This tool tests the activated hardening
#    Copyright (C) 2026  Christopher Klooz
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# This is a selftest for the tool "harden" once hardening has been activated.
# This test will be done automatically after activation.
# Whereas the maintainers keep testing "harden" before releases and
# keep adjusting and tailoring it to new releases and changes in the
# environment, it is not possible to verify each behavior of each context
# in each environment with each potential customization:
# therefore, users are welcome to occasionally run the selftest themselves
# (e.g., after upgrading to a new release of their operating system),
# and report if the selftest finds issues.
#
# Selftests are in an early stage of development: they don't pose a risk
# to the stability of the release or the hardening (they work
# in read-only modes), but it cannot be excluded that they do not yet verify
# all security hardening measures reliably. The goal is to improve
# the selftests over time and make their results binding.
#
# While this might change in future releases, for now the selftests
# aim to emphasize on the issues a user might not experience themselves:
# find out what the users would not find out on themselves.
#
# At some point, the selftest should verify if there has been already a reboot
# after "harden activate", and reject to start if there was no reboot yet
#
# This file intentionally omits PEP-8's line length limits in some lines
# because the outcome would be contrary to the purpose of the limitation

# WHEN THE PACKAGE IS RENAMED in version 1.0, BELOW THE PATH
# /usr/share/doc/Fedora-downstream-hardening/ NEEDS TO BE ADJUSTED

from sepolicy import get_login_mappings
from sepolicy import get_all_bools
from os import uname
from os import path
from os import listdir
from os import readlink
from os import geteuid
from subprocess import getoutput


if geteuid() != 0:
    print("This tool needs to run with sudo or as root!")

else:
    # if any selftest does not pass, the value of "selftestpassed" gets 0
    # "selftestfail" collects data of all tests that fail
    selftestpassed = 1
    selftestfail = []

    try:
        # The following tests intentionally do NOT read the parameter as
        # contained in "99-kernel-hardening.conf" but use the static values
        # that need to be adjusted along with "99-kernel-hardening.conf" in
        # order to not fail.
        # The goal is to identify if the file has been manipulated
        # (may it be manipulated intentionally by the user or not) without
        # being aware of all consequences and impacts.
        # "99-kernel-hardening.conf" contains a reference to update the
        # selftests when updating "99-kernel-hardening.conf".
        with open("/proc/sys/kernel/yama/ptrace_scope") as fyama:
            yama = fyama.read().split("\n")
        with open("/proc/sys/kernel/kptr_restrict") as fkptr:
            kptr = fkptr.read().split("\n")
        with open("/proc/sys/net/core/bpf_jit_harden") as fbpfjitharden:
            bpfjitharden = fbpfjitharden.read().split("\n")
        with open("/proc/sys/fs/protected_fifos") as fspf:
            protectedfifos = fspf.read().split("\n")
        with open("/proc/sys/fs/protected_regular") as fspr:
            protectedregular = fspr.read().split("\n")
        if yama[0] != str(2):
            selftestpassed = 0
            selftestfail.append("yama=" + str(yama))
        if kptr[0] != str(2):
            selftestpassed = 0
            selftestfail.append("kptr=" + str(kptr))
        if bpfjitharden[0] != str(2):
            selftestpassed = 0
            selftestfail.append("bpfjitharden=" + str(bpfjitharden))
        if protectedfifos[0] != str(2):
            selftestpassed = 0
            selftestfail.append("protectedfifos=" + str(protectedfifos))
        if protectedregular[0] != str(2):
            selftestpassed = 0
            selftestfail.append("protectedregular=" + str(protectedregular))

        # Order matters for the following: it assumes that all tests of
        # "99-kernel-hardening.conf" have been done, but only these tests
        # have been done yet: if selftestpassed is already 0 at this time,
        # in can thus be assumed that it is worth to test if the file
        # "99-kernel-hardening.conf" has been even created and put in place
        if selftestpassed == 0:
            if path.isfile("/usr/share/doc/Fedora-downstream-hardening/"
                           + "99-kernel-hardening.conf") != True:
                selftestfail.append("99-kernel-hardening.conf_file_exists="
                                    + "false")
            elif path.isfile("/etc/sysctl.d/99-kernel-hardening.conf") != \
            True:
                selftestfail.append("99-kernel-hardening.conf_symlink_exists="
                                    + "false")
            else:
                with open("/usr/share/doc/Fedora-downstream-hardening/"
                          + "99-kernel-hardening.conf") as kharden:
                    kernelhardencontent = kharden.read().split("\n")
                selftestfail.append("99-kernel-hardening.conf_filetail="
                                    + kernelhardencontent[0-5] + "___"
                                    + kernelhardencontent[0-4] + "___"
                                    + kernelhardencontent[0-3] + "___"
                                    + kernelhardencontent[0-2] + "___"
                                    + kernelhardencontent[0-1])
                selftestfail.append("99-kernel-hardening.conf_symlinktarget="
                                    + readlink("/etc/sysctl.d/"
                                               + "99-kernel-hardening.conf"))

        # The following only tests if the default mapping is properly
        # changed by "harden" because a user is unlikely to experience it if
        # that has failed. It does not verify if all accounts of
        # /etc/passwd with /bin/bash are separated and unconfined: it only
        # tests if __default__ is properly mapped to user_u, and if all
        # /home/ users are separated from __default__
        # The tests consider that some users might want to customize
        # confinements of some accounts (e.g., make some accounts staff_u,
        # of add user_u even to the separated entry of an account).
        confinemappings = get_login_mappings()
        checkhomeusers = listdir("/home")
        unconfinedusers = []
        for entry in range(0,len(confinemappings),1):
            if confinemappings[entry]["name"] == "__default__":
                if confinemappings[entry]["seuser"] != "user_u":
                    selftestpassed = 0
                    selftestfail.append(("default confinement mapping="
                                         + str(confinemappings[entry])))
            if confinemappings[entry]["seuser"] == "unconfined_u":
                unconfinedusers.append(confinemappings[entry]["name"])
            # The next 3 "if" relate to the possibility that some users/admins
            # might add confinement to specific user accounts themselves
            if confinemappings[entry]["seuser"] == "staff_u":
                unconfinedusers.append(confinemappings[entry]["name"])
            if confinemappings[entry]["seuser"] == "user_u":
                unconfinedusers.append(confinemappings[entry]["name"])
            if confinemappings[entry]["seuser"] == "sysadm_u":
                unconfinedusers.append(confinemappings[entry]["name"])
        # It intentionally does not check if all separated users
        # are in /home/ but only vice versa because some users/admins
        # might customize this for their own purposes: this shall
        # be allowed and not lead to an error output. This is only
        # to test if the unconfinehomeusers service works fine, not to
        # identify an attack or so.
        # But it is expected that if a deleted user's directory remains
        # in /home/, then the user also remains in /var/spool/mail
        for entry in range(0,len(checkhomeusers),1):
            if checkhomeusers[entry] not in unconfinedusers:
                if checkhomeusers[entry] != "lost+found":
                    if checkhomeusers[entry] not in listdir("/var/spool/mail"):
                        selftestpassed = 0
                        selftestfail.append("HomeUserNotUnconfined="
                                            + checkhomeusers[entry])

        # Check if the SELinux booleans are properly set by "harden"
        sebooleans = get_all_bools()
        for entry in range(0,len(sebooleans),1):
            if sebooleans[entry]["name"] == "deny_ptrace":
                if sebooleans[entry]["state"] != True:
                    selftestpassed = 0
                    selftestfail.append(("SELinux deny_ptrace boolean="
                                         + str(sebooleans[entry])))

        # Check if all binaries are in place
        existingbinaries = listdir("/usr/bin")
        hardenselftestavailability = 0
        hardenavailability = 0
        unconfinehomeusersavailability = 0
        for entry in range(0,len(existingbinaries),1):
            if "unconfinehomeusers" in existingbinaries[entry]:
                unconfinehomeusersavailability = 1
            if "harden" in existingbinaries[entry]:
                hardenavailability = 1
            if "harden-selftest" in existingbinaries[entry]:
                hardenselftestavailability = 1
        if hardenselftestavailability == 0:
            selftestpassed = 0
            selftestfail.append(("hardenselftestbin"
                                 + str(hardenselftestavailability)))
        if hardenavailability == 0:
            selftestpassed = 0
            selftestfail.append(("hardenbin" + str(hardenavailability)))
        if unconfinehomeusersavailability == 0:
            selftestpassed = 0
            selftestfail.append(("unconfinehomeusersbin"
                                 + str(unconfinehomeusersavailability)))

        # Check if the firewall configuration has been hardened
        # I fall back intentionally to using the command line tool/bash
        # for the purpose of the test
        if "udp" in getoutput("firewall-cmd --list-ports"):
            selftestpassed = 0
            selftestfail.append("udpInFirewallOpenPorts")
        if "tcp" in getoutput("firewall-cmd --list-ports"):
            selftestpassed = 0
            selftestfail.append("tcpInFirewallOpenPorts")
        if "firewalld.conf.prehardening" not in listdir("/etc/firewalld/"):
            selftestpassed = 0
            selftestfail.append("conf.prehardeningFirewalldConfigNotExisting")
        if "DefaultZone=Public" not in getoutput("cat /etc/firewalld/firewalld.conf.prehardening | grep -v \"#DefaultZone=Public\""):
            selftestpassed = 0
            selftestfail.append("conf.prehardeningDefaultZoneLineNotExisting")

        if getoutput("firewall-cmd --get-default-zone") != "public":
            selftestpassed = 0
            selftestfail.append("zoneNotPublic")


        # Check if the systemd paths are active and services loaded
        # I fall back intentionally to using the command line tool/bash
        # for the purpose of the test
        if "Active: active" not in getoutput("systemctl status "
                                             + "unconfinehomeusers.path"):
            selftestpassed = 0
            selftestfail.append("unconfinehomeusers.pathNotActiveRunning")
        if "Active: active" not in getoutput("systemctl status "
                                             + "hardenupdate.path"):
            selftestpassed = 0
            selftestfail.append("hardenupdate.pathNotActiveRunning")
        if "Loaded: loaded" not in getoutput("systemctl status "
                                             + "unconfinehomeusers.service"):
            selftestpassed = 0
            selftestfail.append("unconfinehomeusers.serviceNotActiveLoaded")
        if "Loaded: loaded" not in getoutput("systemctl status "
                                             + "hardenupdate.service"):
            selftestpassed = 0
            selftestfail.append("hardenupdate.serviceNotActiveLoaded")
        if "Active: failed" in getoutput("systemctl status "
                                         + "unconfinehomeusers.service"):
            selftestpassed = 0
            selftestfail.append("unconfinehomeusers.serviceContainsFail")
        if "Active: failed" in getoutput("systemctl status "
                                         + "hardenupdate.service"):
            selftestpassed = 0
            selftestfail.append("hardenupdate.serviceContainsFail")

        # Check if noexec is enabled on /tmp and /home and report if not:
        # this is by default disabled, so it is not always a fail if the two
        # are not noexec (users need to enable the two with a separate
        # command -> see "harden")
        selftestnoexecstatus=[]
        # Unlike selftestpassed, this is not a boolean-like value:
        # the selftestnoexecpass value increases with each error
        selftestnoexecpass = 1
        selftestnoexecenabled = 0
        homemountexists = 0
        if "tmp.mount.d" in listdir("/etc/systemd/system"):
            if "override.conf" in listdir("/etc/systemd/system/tmp.mount.d"):
                cotmp = getoutput("cat /etc/systemd/system/tmp.mount.d/"
                                +"override.conf")
                if "[Mount]\nOptions=" != cotmp[0:16]:
                    selftestnoexecpass = selftestnoexecpass + 2
                    selftestnoexecstatus.append("confcat.mountOptionsTmp")
                if "noexec" not in cotmp:
                    selftestnoexecpass = selftestnoexecpass + 2
                    selftestnoexecstatus.append("confcat.noexecHome")
                cattmp = getoutput("systemctl cat tmp.mount | grep Options=")\
                        .split("\n")
                if "noexec" not in cattmp[len(cattmp)-1]:
                    selftestnoexecpass = selftestnoexecpass + 2
                    selftestnoexecstatus.append("sysctlcat.noexecTmp")
                if "Options=" != cattmp[len(cattmp)-1][0:8]:
                    selftestnoexecpass = selftestnoexecpass + 2
                    selftestnoexecstatus.append("sysctlcat.optionsTmp")
                selftestnoexecenabled = selftestnoexecenabled+1
        if "command not found" not in getoutput("dnf"):
            if "home.mount.d" in listdir("/etc/systemd/system"):
                if "override.conf" in listdir("/etc/systemd/system/home.mount.d"):
                    cohome = getoutput("cat /etc/systemd/system/home.mount.d/"
                                    +"override.conf")
                    if "[Mount]\nOptions=" != cohome[0:16]:
                        selftestnoexecpass = selftestnoexecpass + 2
                        selftestnoexecstatus.append("confcat.d.mountOptionsHome")
                    if "noexec" not in cohome:
                        selftestnoexecpass = selftestnoexecpass + 2
                        selftestnoexecstatus.append("confcat.d.noexecHome")
                    catmount = getoutput("systemctl cat home.mount | grep Options=")\
                            .split("\n")
                    if "noexec" not in catmount[len(catmount)-1]:
                        selftestnoexecpass = selftestnoexecpass + 2
                        selftestnoexecstatus.append("sysctlcat.d.noexecHome")
                    if "Options=" != catmount[len(catmount)-1][0:8]:
                        selftestnoexecpass = selftestnoexecpass + 2
                        selftestnoexecstatus.append("sysctlcat.d.optionsHome")
                    selftestnoexecenabled = selftestnoexecenabled+1
            # If there is no separated /home mount point,
            # selftestnoexecenabled remains 0: that's relevant to find out
            # why selftestnoexecenabled is 1 rather than 0 or 2
            if "/home" in getoutput("cat /etc/fstab | grep home"):
                if "#" not in getoutput("cat /etc/fstab | grep \"/home\""
                                        + "| cut -c1-1 | grep \"#\""):
                    homemountexists = 1
        if "command not found" in getoutput("dnf"):
            if "var-home.mount.d" in listdir("/etc/systemd/system"):
                if "override.conf" in listdir("/etc/systemd/system/var-home.mount.d"):
                    cohome = getoutput("cat /etc/systemd/system/var-home.mount.d/"
                                    +"override.conf")
                    if "[Mount]\nOptions=" != cohome[0:16]:
                        selftestnoexecpass = selftestnoexecpass + 2
                        selftestnoexecstatus.append("confcat.nd.mountOptionsHome")
                    if "noexec" not in cohome:
                        selftestnoexecpass = selftestnoexecpass + 2
                        selftestnoexecstatus.append("confcat.nd.noexecHome")
                    catmount = getoutput("systemctl cat var-home.mount | grep Options=")\
                            .split("\n")
                    if "noexec" not in catmount[len(catmount)-1]:
                        selftestnoexecpass = selftestnoexecpass + 2
                        selftestnoexecstatus.append("sysctlcat.nd.noexecHome")
                    if "Options=" != catmount[len(catmount)-1][0:8]:
                        selftestnoexecpass = selftestnoexecpass + 2
                        selftestnoexecstatus.append("sysctlcat.nd.optionsHome")
                    selftestnoexecenabled = selftestnoexecenabled+1
            # If there is no separated /home mount point,
            # selftestnoexecenabled remains 0: that's relevant to find out
            # why selftestnoexecenabled is 1 rather than 0 or 2
            if "/home" in getoutput("cat /etc/fstab | grep home"):
                if "#" not in getoutput("cat /etc/fstab | grep \"/home\""
                                        + "| cut -c1-1 | grep \"#\""):
                    homemountexists = 1


    except:
        selftestpassed = 0
        selftestfail.append("selftest_try=failed")

    # If anything fails, tell the user and provide the data of all fails
    # along with data of the environment that might become relevant
    # in troubleshooting
    if selftestpassed == 0:
        with open("/proc/sys/kernel/tainted") as ftaint:
            tainted = "kernel tainted value: "+ftaint.read().split("\n")[0]
        print("This selftest is only applicable if you have rebooted AFTER")
        print("activating harden with \"harden activate\": before rebooting,")
        print("the selftest will always fail intentionally! Consider the")
        print("following only if you have already rebooted:")
        print()
        print("At least one selftest has failed!")
        print("Please check out either yourself what is going on")
        print("or open a ticket at the repository:")
        print("https://github.com/py0xc3/Fedora-downstream-hardening/")
        print("Please copy/paste all the following information:")
        print(tainted)
        print(uname())
        print(selftestfail)
        print("... plus an elaboration of potential impacts/issues you")
        print("experienced and everything else you think might be relevant")
        print("to find the problem. You are also welcome to add an output of")
        print("\"sudo journalctl --boot=0 --no-hostname\"")
        print("-> the journalctl command assumes the current boot is affected")
        print()
        print("Please ensure the output does not contain anything you consider")
        print("private! If so, please replace the private terms with the term")
        print("ANON8461 so that we know when analyzing the data")
    if selftestpassed == 1:
        print("All selftests pass! Everything works fine!")
        print()
        if selftestnoexecpass == 17:
            print("Selftest indicates harden's \"noexec\" is not enabled:")
            print("this is not enabled by default with \"harden activate\".")
            print("If you just did \"harden activate\", then")
            print("everything is fine. If you enabled additionally \"noexec\"")
            print("with \"harden activate-noexec-now\", then something")
            print("seems wrong and you might consider to open a bug report:")
            print("mention \"selftestnoexecpass\" has value 17. File this at:")
            print("https://github.com/py0xc3/Fedora-downstream-hardening/")
        if selftestnoexecpass > 1:
            if selftestnoexecpass < 17:
                print("The selftest indicates you have enabled either")
                print("yourself or harden's '\"noexec\", but it is not fully")
                print("enabled the way it is intended by the harden tool:")
                print("\"harden activate\" does not enable this by default.")
                print("If you have manually enabled it by yourself without")
                print("harden, you can IGNORE this message. But if you have")
                print("enabled it through harden's")
                print("\"harden activate-noexec-now\", then something is")
                print("wrong. You should consider to open a bug report at:")
                print("https://github.com/py0xc3/Fedora-downstream-hardening/")
                print("Mention that you have the \"selftestnoexecpass\" value")
                print(selftestnoexecpass, " and also add the following line")
                print("within the [] brackets to your report:")
                print(selftestnoexecstatus)
        if selftestnoexecpass == 1:
            if selftestnoexecenabled == 0:
                print("Harden is activated. It seems you did")
                print("\"harden activate\" successfully.")
                print("But you did not activate additionally harden's noexec")
                print("function. That's fine! For most users, noexec is too")
                print("much and breaks stuff!")
            if selftestnoexecenabled == 2:
                print("Harden is activated. It seems you did")
                print("\"harden activate\" successfully. And you also did")
                print("\"harden activate-noexec-now\": \"noexec\" is also")
                print("enabled on /home and /tmp")
            if selftestnoexecenabled == 1:
                # If only /home or /tmp is enabled and the other one broke, it
                # can occur that "selftestnoexecpass" is 1 because the
                # respective if-clauses have not been triggered at all, and
                # thus only the selftests of the working one have been
                # conducted. However, it can also imply that the system's
                # default is noexec on either /home or /tmp but not the other:
                # this occurs on some Fedora variants with /home, which is why
                # /etc/fstab is checked for the file defaults that are not changed
                # by harden in any circumstances
                if selftestnoexecpass == 1:
                    if homemountexists == 1:
                        if "noexec" not in getoutput("cat /etc/fstab | grep \"/home \""):
                            print("The selftest indicates you have enabled either")
                            print("your own or harden's \"noexec\" function, but it is")
                            print("not fully enabled the way it is intended")
                            print("by the harden tool:")
                            print("\"harden activate\" does not enable this by default.")
                            print("If you have manually enabled it by yourself without")
                            print("harden, you can IGNORE this message. But if you have")
                            print("enabled it through harden's")
                            print("\"harden activate-noexec-now\", then something is")
                            print("wrong. You should consider to open a bug report at:")
                            print("https://github.com/py0xc3/Fedora-downstream-hardening/")
                            print("Mention that you have the \"selftestnoexecpass\" value")
                            print(selftestnoexecpass, " and also add the following line")
                            print("within the [] brackets to your report:")
                            print(selftestnoexecstatus)
                            print("Also mention the value of the \"selftestnoexecenabled\":")
                            print(selftestnoexecenabled)
                        if "noexec" in getoutput("cat /etc/fstab | grep \"/home \""):
                            print("Harden is activated. It seems you did")
                            print("\"harden activate\" successfully.")
                            print("But you did not activate additionally harden's noexec")
                            print("function. That's fine! For most users, noexec is too")
                            print("much and breaks stuff! However, /home seems to be")
                            print("already by default (or by you) set to noexec!")
                    if homemountexists == 0:
                        print("Harden is activated. It seems you did")
                        print("\"harden activate\" successfully. And you also did")
                        print("\"harden activate-noexec-now\": \"noexec\" is also")
                        print("enabled on /tmp, but NOT on /home because you")
                        print("do NOT have a separated mountpoint on /home: this")
                        print("still enables some of the noexec security advantages.")
                        print("In this situation, no noexec on /home is NOT an error.")
